services:
    custom-rpi-image:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: rpi-tradingstrategy-ai:latest
        volumes:
            - ./custom-rpi-image:/home/imagegen/custom-rpi-image
            - ./jupyter-notebook-app:/home/imagegen/jupyter-notebook-app